create extension if not exists "pgcrypto";

do $$ begin
  create type public.user_role as enum ('admin', 'seller');
exception when duplicate_object then null; end $$;
do $$ begin
  create type public.product_type as enum ('terrarium', 'workshop', 'supply');
exception when duplicate_object then null; end $$;
do $$ begin
  create type public.sale_status as enum ('pending', 'paid', 'cancelled', 'refunded');
exception when duplicate_object then null; end $$;
do $$ begin
  create type public.payment_method as enum ('pix', 'card', 'cash');
exception when duplicate_object then null; end $$;
do $$ begin
  create type public.stock_movement_type as enum ('opening_balance', 'purchase', 'manual_in', 'manual_out', 'sale', 'production', 'adjustment', 'cancellation');
exception when duplicate_object then null; end $$;

create table if not exists public.stores (
  id uuid primary key default gen_random_uuid(), name varchar(120) not null,
  cnpj varchar(18) unique, email varchar(254) not null, phone varchar(30) not null,
  address_line varchar(200) not null, city varchar(100) not null, state char(2) not null,
  active boolean not null default true, created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  username varchar(80) unique not null, display_name varchar(120) not null,
  email varchar(254) unique, active boolean not null default true,
  last_login_at timestamptz, created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.store_users (
  store_id uuid references public.stores(id) on delete cascade,
  user_id uuid references public.users(id) on delete cascade,
  role public.user_role not null, created_at timestamptz not null default now(),
  primary key (store_id, user_id)
);
create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(), name varchar(100) not null,
  slug varchar(100) unique not null, product_type public.product_type not null,
  sellable boolean not null default true, sort_order smallint not null default 0,
  active boolean not null default true
);
create table if not exists public.products (
  id uuid primary key default gen_random_uuid(), store_id uuid not null references public.stores(id),
  category_id uuid references public.categories(id), type public.product_type not null,
  name varchar(160) not null, sku varchar(60) not null, cost_price numeric(12,2) not null default 0 check (cost_price >= 0),
  sale_price numeric(12,2) check (sale_price is null or sale_price >= 0), cost_unit varchar(20) not null default 'un',
  sellable boolean not null default false, image_url text, active boolean not null default true,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  unique (store_id, sku), check (not sellable or sale_price is not null)
);
create table if not exists public.inventory_levels (
  product_id uuid primary key references public.products(id) on delete cascade,
  quantity integer not null default 0 check (quantity >= 0),
  minimum_quantity integer not null default 0 check (minimum_quantity >= 0),
  updated_at timestamptz not null default now()
);
create table if not exists public.sales (
  id uuid primary key default gen_random_uuid(), store_id uuid not null references public.stores(id),
  sale_number bigint generated by default as identity, status public.sale_status not null default 'pending',
  subtotal numeric(12,2) not null check (subtotal >= 0), discount_percent numeric(5,2) not null default 0 check (discount_percent between 0 and 100),
  discount_amount numeric(12,2) not null default 0 check (discount_amount >= 0), total numeric(12,2) not null check (total >= 0),
  created_by uuid not null references public.users(id), paid_at timestamptz,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.sale_items (
  id uuid primary key default gen_random_uuid(), sale_id uuid not null references public.sales(id) on delete cascade,
  product_id uuid not null references public.products(id), product_name_snapshot varchar(160) not null,
  sku_snapshot varchar(60) not null, unit_price numeric(12,2) not null check (unit_price >= 0),
  unit_cost_snapshot numeric(12,2) not null default 0, quantity integer not null check (quantity > 0),
  line_total numeric(12,2) not null check (line_total >= 0)
);
create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(), sale_id uuid not null references public.sales(id) on delete cascade,
  method public.payment_method not null, amount numeric(12,2) not null check (amount > 0),
  status varchar(30) not null default 'pending', external_reference varchar(160),
  paid_at timestamptz, created_at timestamptz not null default now()
);
create table if not exists public.stock_movements (
  id uuid primary key default gen_random_uuid(), store_id uuid not null references public.stores(id),
  product_id uuid not null references public.products(id), type public.stock_movement_type not null,
  quantity_delta integer not null, quantity_before integer not null check (quantity_before >= 0),
  quantity_after integer not null check (quantity_after >= 0), unit_cost numeric(12,2),
  sale_id uuid references public.sales(id), notes text, created_by uuid not null references public.users(id),
  created_at timestamptz not null default now()
);
create table if not exists public.store_settings (
  store_id uuid primary key references public.stores(id) on delete cascade,
  low_stock_alert_enabled boolean not null default true, default_low_stock_quantity integer not null default 5,
  sales_alert_email boolean not null default true, sales_alert_whatsapp boolean not null default true,
  weekly_report_enabled boolean not null default true, weekly_report_weekday smallint not null default 1,
  timezone varchar(50) not null default 'America/Sao_Paulo', updated_at timestamptz not null default now()
);
create table if not exists public.notification_preferences (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade,
  store_id uuid not null references public.stores(id) on delete cascade, event_type varchar(50) not null,
  channel varchar(20) not null, enabled boolean not null default true,
  unique (user_id, store_id, event_type, channel)
);

create or replace function public.set_updated_at() returns trigger language plpgsql security invoker as $$
begin new.updated_at = now(); return new; end $$;
drop trigger if exists stores_updated_at on public.stores;
create trigger stores_updated_at before update on public.stores for each row execute function public.set_updated_at();
drop trigger if exists users_updated_at on public.users;
create trigger users_updated_at before update on public.users for each row execute function public.set_updated_at();
drop trigger if exists products_updated_at on public.products;
create trigger products_updated_at before update on public.products for each row execute function public.set_updated_at();

create or replace function public.handle_new_user() returns trigger
language plpgsql security definer set search_path = public as $$
declare default_store uuid;
begin
  insert into public.users (id, username, display_name, email)
  values (new.id, coalesce(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1)), coalesce(new.raw_user_meta_data->>'display_name', split_part(new.email, '@', 1)), new.email)
  on conflict (id) do update set email = excluded.email, updated_at = now();
  select id into default_store from public.stores where cnpj = '12345678000199' limit 1;
  if default_store is null then
    insert into public.stores (name, cnpj, email, phone, address_line, city, state)
    values ('Bromélia Terrários', '12345678000199', 'ola@bromeliaterrarios.com.br', '(11) 99999-8888', 'Rua das Bromélias, 42', 'São Paulo', 'SP')
    returning id into default_store;
  end if;
  insert into public.store_users (store_id, user_id, role) values (default_store, new.id, 'admin')
  on conflict (store_id, user_id) do nothing;
  return new;
end $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

create or replace function public.is_store_member(target_store uuid) returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.store_users where store_id = target_store and user_id = auth.uid());
$$;

alter table public.stores enable row level security;
alter table public.users enable row level security;
alter table public.store_users enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.inventory_levels enable row level security;
alter table public.sales enable row level security;
alter table public.sale_items enable row level security;
alter table public.payments enable row level security;
alter table public.stock_movements enable row level security;
alter table public.store_settings enable row level security;
alter table public.notification_preferences enable row level security;

create policy "members can read stores" on public.stores for select using (public.is_store_member(id));
create policy "users can read own profile" on public.users for select using (id = auth.uid());
create policy "members can read memberships" on public.store_users for select using (user_id = auth.uid() or public.is_store_member(store_id));
create policy "members manage categories" on public.categories for all using (exists (select 1 from public.products p where p.category_id = categories.id and public.is_store_member(p.store_id)) or auth.uid() is not null) with check (auth.uid() is not null);
create policy "members manage products" on public.products for all using (public.is_store_member(store_id)) with check (public.is_store_member(store_id));
create policy "members manage inventory" on public.inventory_levels for all using (exists (select 1 from public.products p where p.id = product_id and public.is_store_member(p.store_id))) with check (exists (select 1 from public.products p where p.id = product_id and public.is_store_member(p.store_id)));
create policy "members manage sales" on public.sales for all using (public.is_store_member(store_id)) with check (public.is_store_member(store_id) and created_by = auth.uid());
create policy "members manage sale items" on public.sale_items for all using (exists (select 1 from public.sales s where s.id = sale_id and public.is_store_member(s.store_id))) with check (exists (select 1 from public.sales s where s.id = sale_id and public.is_store_member(s.store_id)));
create policy "members manage payments" on public.payments for all using (exists (select 1 from public.sales s where s.id = sale_id and public.is_store_member(s.store_id))) with check (exists (select 1 from public.sales s where s.id = sale_id and public.is_store_member(s.store_id)));
create policy "members manage movements" on public.stock_movements for all using (public.is_store_member(store_id)) with check (public.is_store_member(store_id) and created_by = auth.uid());
create policy "members manage settings" on public.store_settings for all using (public.is_store_member(store_id)) with check (public.is_store_member(store_id));
create policy "users manage own preferences" on public.notification_preferences for all using (user_id = auth.uid()) with check (user_id = auth.uid() and public.is_store_member(store_id));

create index if not exists products_store_active_idx on public.products(store_id, sellable, active);
create index if not exists products_category_idx on public.products(category_id);
create index if not exists sales_store_created_idx on public.sales(store_id, created_at desc);
create index if not exists sales_store_status_idx on public.sales(store_id, status, paid_at desc);

create or replace function public.finalize_sale(
  p_store_id uuid, p_payment_method public.payment_method,
  p_discount_percent numeric, p_items jsonb
) returns uuid language plpgsql security definer set search_path = public as $$
declare
  current_user_id uuid := auth.uid();
  sale_id uuid;
  item jsonb;
  product_row record;
  subtotal numeric(12,2) := 0;
  discount_amount numeric(12,2);
  sale_total numeric(12,2);
  before_quantity integer;
  requested_quantity integer;
begin
  if current_user_id is null or not public.is_store_member(p_store_id) then
    raise exception 'Usuário não autorizado para esta loja';
  end if;
  if jsonb_array_length(p_items) = 0 then raise exception 'A venda precisa ter itens'; end if;
  for item in select * from jsonb_array_elements(p_items) loop
    requested_quantity := (item->>'quantity')::integer;
    if requested_quantity <= 0 then raise exception 'Quantidade inválida'; end if;
    select p.*, coalesce(il.quantity, 0) as available_quantity
      into product_row from public.products p
      left join public.inventory_levels il on il.product_id = p.id
      where p.id = (item->>'product_id')::uuid and p.store_id = p_store_id and p.active and p.sellable
      for update;
    if not found then raise exception 'Produto não encontrado'; end if;
    if product_row.available_quantity < requested_quantity then raise exception 'Estoque insuficiente para %', product_row.name; end if;
    subtotal := subtotal + (product_row.sale_price * requested_quantity);
  end loop;
  if p_discount_percent < 0 or p_discount_percent > 100 then raise exception 'Desconto inválido'; end if;
  discount_amount := round(subtotal * p_discount_percent / 100, 2);
  sale_total := subtotal - discount_amount;
  insert into public.sales (store_id, status, subtotal, discount_percent, discount_amount, total, created_by, paid_at)
  values (p_store_id, 'paid', subtotal, p_discount_percent, discount_amount, sale_total, current_user_id, now())
  returning id into sale_id;
  for item in select * from jsonb_array_elements(p_items) loop
    requested_quantity := (item->>'quantity')::integer;
    select p.*, il.quantity into product_row from public.products p
      join public.inventory_levels il on il.product_id = p.id
      where p.id = (item->>'product_id')::uuid and p.store_id = p_store_id for update;
    before_quantity := product_row.quantity;
    insert into public.sale_items (sale_id, product_id, product_name_snapshot, sku_snapshot, unit_price, unit_cost_snapshot, quantity, line_total)
    values (sale_id, product_row.id, product_row.name, product_row.sku, product_row.sale_price, product_row.cost_price, requested_quantity, product_row.sale_price * requested_quantity);
    update public.inventory_levels set quantity = quantity - requested_quantity, updated_at = now() where product_id = product_row.id;
    insert into public.stock_movements (store_id, product_id, type, quantity_delta, quantity_before, quantity_after, sale_id, created_by)
    values (p_store_id, product_row.id, 'sale', -requested_quantity, before_quantity, before_quantity - requested_quantity, sale_id, current_user_id);
  end loop;
  insert into public.payments (sale_id, method, amount, status, paid_at)
  values (sale_id, p_payment_method, sale_total, 'approved', now());
  return sale_id;
end $$;
revoke all on function public.finalize_sale(uuid, public.payment_method, numeric, jsonb) from public;
grant execute on function public.finalize_sale(uuid, public.payment_method, numeric, jsonb) to authenticated;

create or replace function public.ensure_current_user_setup() returns uuid
language plpgsql security definer set search_path = public as $$
declare store_id uuid; user_email text;
begin
  if auth.uid() is null then raise exception 'Usuário não autenticado'; end if;
  select email into user_email from auth.users where id = auth.uid();
  insert into public.users (id, username, display_name, email)
  values (auth.uid(), split_part(coalesce(user_email, 'usuario'), '@', 1), split_part(coalesce(user_email, 'usuario'), '@', 1), user_email)
  on conflict (id) do update set email = excluded.email, updated_at = now();
  select su.store_id into store_id from public.store_users su where su.user_id = auth.uid() limit 1;
  if store_id is null then
    select id into store_id from public.stores where cnpj = '12345678000199' limit 1;
    if store_id is null then
      insert into public.stores (name, cnpj, email, phone, address_line, city, state)
      values ('Bromélia Terrários', '12345678000199', 'ola@bromeliaterrarios.com.br', '(11) 99999-8888', 'Rua das Bromélias, 42', 'São Paulo', 'SP')
      returning id into store_id;
    end if;
    insert into public.store_users (store_id, user_id, role) values (store_id, auth.uid(), 'admin')
    on conflict do nothing;
  end if;
  insert into public.store_settings (store_id) values (store_id) on conflict do nothing;
  return store_id;
end $$;
grant execute on function public.ensure_current_user_setup() to authenticated;
